// Mocks generated by Mockito 5.4.5 from annotations
// in car_rental/test/car_details_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:car_rental/features/booking/data/data_source/local_data_source/car_details_local_data_source.dart'
    as _i7;
import 'package:car_rental/features/booking/data/data_source/remote_data_source/car_details_remote_data_source.dart'
    as _i4;
import 'package:car_rental/features/booking/data/model/car_details_model.dart'
    as _i3;
import 'package:car_rental/features/booking/data/model/host_model.dart' as _i2;
import 'package:car_rental/features/booking/data/model/pickup_location_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHostModel_0 extends _i1.SmartFake implements _i2.HostModel {
  _FakeHostModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarDetailsModel_1 extends _i1.SmartFake
    implements _i3.CarDetailsModel {
  _FakeCarDetailsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CarDetailsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarDetailsRemoteDataSource extends _i1.Mock
    implements _i4.CarDetailsRemoteDataSource {
  MockCarDetailsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.HostModel> getHost(dynamic carId) => (super.noSuchMethod(
        Invocation.method(
          #getHost,
          [carId],
        ),
        returnValue: _i5.Future<_i2.HostModel>.value(_FakeHostModel_0(
          this,
          Invocation.method(
            #getHost,
            [carId],
          ),
        )),
      ) as _i5.Future<_i2.HostModel>);

  @override
  _i5.Future<List<_i6.PickupLocationModel>> getLocations(dynamic carId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocations,
          [carId],
        ),
        returnValue: _i5.Future<List<_i6.PickupLocationModel>>.value(
            <_i6.PickupLocationModel>[]),
      ) as _i5.Future<List<_i6.PickupLocationModel>>);

  @override
  _i5.Future<_i3.CarDetailsModel> getCarDetails(dynamic carId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCarDetails,
          [carId],
        ),
        returnValue:
            _i5.Future<_i3.CarDetailsModel>.value(_FakeCarDetailsModel_1(
          this,
          Invocation.method(
            #getCarDetails,
            [carId],
          ),
        )),
      ) as _i5.Future<_i3.CarDetailsModel>);
}

/// A class which mocks [CarDetailsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarDetailsLocalDataSource extends _i1.Mock
    implements _i7.CarDetailsLocalDataSource {
  MockCarDetailsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheCarDetails(
    String? carId,
    _i3.CarDetailsModel? carDetails,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCarDetails,
          [
            carId,
            carDetails,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.CarDetailsModel> getCachedCarDetails(String? carId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedCarDetails,
          [carId],
        ),
        returnValue:
            _i5.Future<_i3.CarDetailsModel>.value(_FakeCarDetailsModel_1(
          this,
          Invocation.method(
            #getCachedCarDetails,
            [carId],
          ),
        )),
      ) as _i5.Future<_i3.CarDetailsModel>);

  @override
  _i5.Future<void> cacheHost(
    String? carId,
    _i2.HostModel? host,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheHost,
          [
            carId,
            host,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.HostModel> getCachedHost(String? carId) => (super.noSuchMethod(
        Invocation.method(
          #getCachedHost,
          [carId],
        ),
        returnValue: _i5.Future<_i2.HostModel>.value(_FakeHostModel_0(
          this,
          Invocation.method(
            #getCachedHost,
            [carId],
          ),
        )),
      ) as _i5.Future<_i2.HostModel>);

  @override
  _i5.Future<void> cacheLocations(
    String? carId,
    List<_i6.PickupLocationModel>? locations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheLocations,
          [
            carId,
            locations,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.PickupLocationModel>> getCachedLocations(String? carId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedLocations,
          [carId],
        ),
        returnValue: _i5.Future<List<_i6.PickupLocationModel>>.value(
            <_i6.PickupLocationModel>[]),
      ) as _i5.Future<List<_i6.PickupLocationModel>>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
