// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZgwz65Phem5HcZyFAUf9eksC5UPBIgI',
    appId: '1:356033349652:web:afee0163dbaabfeddc7f01',
    messagingSenderId: '356033349652',
    projectId: 'car-rental-98504',
    authDomain: 'car-rental-98504.firebaseapp.com',
    storageBucket: 'car-rental-98504.firebasestorage.app',
    measurementId: 'G-4XBRYY4Y5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYtRXXPVwmO6xNn7LwGespno5VKIzeW-I',
    appId: '1:892666697069:android:1c4b99df0c4c66503bf664',
    messagingSenderId: '892666697069',
    projectId: 'car-rental-c3a92',
    storageBucket: 'car-rental-c3a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvJ0CjCGdggBCKqFxRcmJH7eagqxlWX0',
    appId: '1:892666697069:ios:b781e32180c791df3bf664',
    messagingSenderId: '892666697069',
    projectId: 'car-rental-c3a92',
    storageBucket: 'car-rental-c3a92.firebasestorage.app',
    iosBundleId: 'com.elsaghier.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtbQRVIOVKPViHRFZgEquWOJvSwqrE5W8',
    appId: '1:356033349652:ios:75f13a821ab21e01dc7f01',
    messagingSenderId: '356033349652',
    projectId: 'car-rental-98504',
    storageBucket: 'car-rental-98504.firebasestorage.app',
    iosBundleId: 'com.elsaghier.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGZgwz65Phem5HcZyFAUf9eksC5UPBIgI',
    appId: '1:356033349652:web:f96cbcb0fb9c1390dc7f01',
    messagingSenderId: '356033349652',
    projectId: 'car-rental-98504',
    authDomain: 'car-rental-98504.firebaseapp.com',
    storageBucket: 'car-rental-98504.firebasestorage.app',
    measurementId: 'G-Z18DB3SMLF',
  );
}