// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcB-sXol9jyqio-AGw3CH_BTVaJJC18pk',
    appId: '1:892666697069:web:9ac9f11b7c13f7953bf664',
    messagingSenderId: '892666697069',
    projectId: 'car-rental-c3a92',
    authDomain: 'car-rental-c3a92.firebaseapp.com',
    storageBucket: 'car-rental-c3a92.firebasestorage.app',
    measurementId: 'G-LZQNWEB9N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYtRXXPVwmO6xNn7LwGespno5VKIzeW-I',
    appId: '1:892666697069:android:bc874e0b119c017f3bf664',
    messagingSenderId: '892666697069',
    projectId: 'car-rental-c3a92',
    storageBucket: 'car-rental-c3a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvJ0CjCGdggBCKqFxRcmJH7eagqxlWX0',
    appId: '1:892666697069:ios:b781e32180c791df3bf664',
    messagingSenderId: '892666697069',
    projectId: 'car-rental-c3a92',
    storageBucket: 'car-rental-c3a92.firebasestorage.app',
    iosBundleId: 'com.elsaghier.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcB-sXol9jyqio-AGw3CH_BTVaJJC18pk',
    appId: '1:892666697069:web:37440d8426f7f6db3bf664',
    messagingSenderId: '892666697069',
    projectId: 'car-rental-c3a92',
    authDomain: 'car-rental-c3a92.firebaseapp.com',
    storageBucket: 'car-rental-c3a92.firebasestorage.app',
    measurementId: 'G-YJ3B12Z5ND',
  );
}
